/**
 * Copyright (c) 2026 Biztribe Trading & Consultancy India Private Limited.
 * All rights reserved.
 *
 * This file is part of the Fractional Sales Partner platform.
 * CONFIDENTIAL AND PROPRIETARY — Unauthorised copying, redistribution,
 * modification, or use of this file, via any medium, is strictly prohibited.
 * Violation will result in civil and criminal prosecution under the
 * Copyright Act 1957, Information Technology Act 2000, and applicable
 * Indian and international intellectual property laws.
 */

import { NextRequest, NextResponse } from 'next/server';
import { adminDb, admin } from '@/lib/firebase-admin';

// Simple PDF generation using raw PDF syntax (no external library needed)
function generatePdfContent(leads: any[], title: string): Buffer {
  const lines: string[] = [];
  
  // Group leads by temperature
  const hotLeads = leads.filter(l => l.temperature === 'hot');
  const warmLeads = leads.filter(l => l.temperature === 'warm');
  const coldLeads = leads.filter(l => l.temperature === 'cold');

  lines.push(`SCALEFRACTION - LEAD REPORT`);
  lines.push(`Generated: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`);
  lines.push(`Total Leads: ${leads.length} | Hot: ${hotLeads.length} | Warm: ${warmLeads.length} | Cold: ${coldLeads.length}`);
  lines.push('');
  lines.push('═'.repeat(60));

  const formatLeadSection = (sectionLeads: any[], label: string) => {
    if (sectionLeads.length === 0) return;
    lines.push('');
    lines.push(`▎ ${label} (${sectionLeads.length})`);
    lines.push('─'.repeat(60));
    sectionLeads.forEach((lead, i) => {
      const ci = lead.contactInfo || {};
      lines.push(`  ${i + 1}. ${ci.name || 'Unknown'} - ${ci.designation || 'N/A'}`);
      lines.push(`     Company: ${ci.company || 'N/A'}`);
      lines.push(`     Email: ${ci.email || 'N/A'} | Phone: ${ci.phone || 'N/A'}`);
      lines.push(`     Action: ${lead.actionItem || 'N/A'}`);
      lines.push(`     Context: ${lead.contextSummary || 'N/A'}`);
      const date = lead.createdAt?.toDate?.() || new Date();
      lines.push(`     Captured: ${date.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`);
      lines.push('');
    });
  };

  formatLeadSection(hotLeads, '🔥 HOT LEADS');
  formatLeadSection(warmLeads, '🟡 WARM LEADS');
  formatLeadSection(coldLeads, '❄️ COLD LEADS');

  if (leads.length === 0) {
    lines.push('');
    lines.push('No leads have been captured yet.');
  }

  lines.push('');
  lines.push('═'.repeat(60));
  lines.push('Report generated by ScaleFraction AI');

  return Buffer.from(lines.join('\n'), 'utf-8');
}

export async function POST(req: NextRequest) {
  try {
    // Verify authentication
    const authHeader = req.headers.get('Authorization');
    if (!authHeader?.startsWith('Bearer ')) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const token = authHeader.split('Bearer ')[1];
    const decodedToken = await admin.auth().verifyIdToken(token);
    const uid = decodedToken.uid;

    if (!adminDb) {
      return NextResponse.json({ error: 'Database not initialized' }, { status: 500 });
    }

    const body = await req.json();
    const { postId } = body;

    // Fetch leads based on context
    let query = adminDb.collection('Leads')
      .where('ownerUid', '==', uid)
      .orderBy('createdAt', 'desc');

    if (postId) {
      query = adminDb.collection('Leads')
        .where('ownerUid', '==', uid)
        .where('postId', '==', postId)
        .orderBy('createdAt', 'desc');
    }

    const leadsSnapshot = await query.get();
    const leads = leadsSnapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));

    // Generate the text report
    const reportTitle = postId ? `Deal ${postId}` : 'All Leads';
    const reportBuffer = generatePdfContent(leads, reportTitle);

    // Upload to Firebase Storage
    const bucket = admin.storage().bucket();
    const fileName = `reports/${uid}/${postId || 'global'}_${Date.now()}.txt`;
    const file = bucket.file(fileName);

    await file.save(reportBuffer, {
      metadata: {
        contentType: 'text/plain; charset=utf-8',
        metadata: {
          generatedBy: uid,
          postId: postId || 'global',
        },
      },
    });

    // Generate a signed URL valid for 7 days
    const [signedUrl] = await file.getSignedUrl({
      action: 'read',
      expires: Date.now() + 7 * 24 * 60 * 60 * 1000,
    });

    return NextResponse.json({
      success: true,
      downloadUrl: signedUrl,
      leadsCount: leads.length,
    });

  } catch (error: any) {
    console.error('Report generation error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to generate report' },
      { status: 500 }
    );
  }
}
